export {default as assign} from './assign'
export {default as document} from './document'
export {default as forEach} from './for-each'
export {default as forIn} from './for-in'
export {default as getType} from './get-type'
export {default as globalThis} from './global-this'
export {default as hasOwn} from './has-own'
export {default as identify} from './identify'
export {default as isArray} from './is-array'
export {default as isArrayLike} from './is-array-like'
// export {default as isLength} from './is-length'
export {default as noop} from './noop'
export {default as returnFalse} from './return-false'
export {default as returnTrue} from './return-true'
export {default as toString} from './to-string'
