export {default as assign} from './assign.js'
export {default as document} from './document.js'
export {default as forEach} from './for-each.js'
export {default as forIn} from './for-in.js'
export {default as getType} from './get-type.js'
export {default as globalThis} from './global-this.js'
export {default as hasOwn} from './has-own.js'
export {default as identify} from './identify.js'
export {default as isArray} from './is-array.js'
export {default as isArrayLike} from './is-array-like.js'
// export {default as isLength} from './is-length.js'
export {default as noop} from './noop.js'
export {default as returnFalse} from './return-false.js'
export {default as returnTrue} from './return-true.js'
export {default as toString} from './to-string.js'
