const NS = 'fu'
const BLOCK = `${NS}-dialog`

export const CONTAINER = BLOCK
export const HEAD = `${BLOCK}__head`
export const TITLE = `${BLOCK}__title`
export const BODY = `${BLOCK}__body`
export const MESSAGE = `${BLOCK}__message`
export const MESSAGE_BODY = `${BLOCK}__message-body`
export const INPUT = `${BLOCK}__input`
export const FOOT = `${BLOCK}__foot`
export const ACTIONS = `${BLOCK}__actions`
export const CLOSE_BTN = `${BLOCK}__close`
export const ACTION = `${BLOCK}__action`
export const ACTION_TYPE_CONFIRM = `${ACTION}--confirm`
export const ACTION_TYPE_CANCEL = `${ACTION}--cancel`
export const DIALOG_TYPE_ALERT = `${BLOCK}--alert`
export const DIALOG_TYPE_CONFIRM = `${BLOCK}--confirm`
export const DIALOG_TYPE_PROMPT = `${BLOCK}--prompt`
