const NS = 'f-dialog'

export const CONTAINER = NS
export const HEAD = NS + '__head'
export const TITLE = NS + '__title'
export const BODY = NS + '__body'
export const MESSAGE = NS + '__message'
export const MESSAGE_BODY = NS + '__message-body'
export const INPUT = NS + '__input'
export const FOOT = NS + '__foot'
export const ACTIONS = NS + '__actions'
export const CLOSE_BTN = NS + '__close'
export const ACTION = NS + '__action'
export const ACTION_TYPE_CONFIRM = ACTION + '--confirm'
export const ACTION_TYPE_CANCEL = ACTION + '--cancel'
export const DIALOG_TYPE_ALERT = NS + '--alert'
export const DIALOG_TYPE_CONFIRM = NS + '--confirm'
export const DIALOG_TYPE_PROMPT = NS + '--prompt'
